"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { TakeHomeResult } from "@/utils/take-home/calculate";
import {
  mergeMonthlyEntry,
  stripAutoGenerated,
} from "@/utils/monthly/merge-recurring";
import type { MonthlyEntry } from "@/types/monthlyPlan";
import { MONTH_NAMES, emptyMonthlyEntry, summariseMonth } from "@/types/monthlyPlan";
import type { SavingsGoal } from "@/types/savingsGoals";
import { RecurringExpense } from "@/types/recurringExpenses";
import { CalendarIcon, GridViewIcon } from "./icons";
import FinanceTrendChart from "./finance-trend-chart";
import TakeHomeCard from "./take-home-card";
import MonthlyDetailView from "./MonthlyDetailView";
import YearlyPlannerSection from "./yearly-planner-section";
import MonthDetailModal from "./month-detail-modal";

type ViewMode = "yearly" | "monthly";

type DashboardClientProps = {
  firstName: string;
  takeHome: TakeHomeResult;
  initialYear: number;
  initialMonthsData: MonthlyEntry[];
  recurringExpenses: RecurringExpense[];
  savingsGoals: SavingsGoal[];
  baseNetMonthly: number;
  currentMonthPay: {
    amount: number;
    payDateLabel: string;
  };
};

export default function DashboardClient({
  firstName,
  takeHome,
  initialYear,
  initialMonthsData,
  recurringExpenses,
  savingsGoals,
  baseNetMonthly,
  currentMonthPay,
}: DashboardClientProps) {
  const router = useRouter();
  const [view, setView] = useState<ViewMode>("yearly");
  const [year, setYear] = useState(initialYear);
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [monthsData, setMonthsData] = useState(initialMonthsData);
  const [modalMonth, setModalMonth] = useState<number | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [showAllMonths, setShowAllMonths] = useState(false);

  useEffect(() => {
    setMonthsData(initialMonthsData);
  }, [initialMonthsData]);

  // This function resolves a monthly entry for a given year and month, merging it with recurring expenses and savings goals.
  // Simply put, a monthly entry refers to the data for a specific month, including expenses, income, and other financial details.
  // The function checks if there's already stored data for that month and year. If there is, it uses that; if not, it creates an empty entry. Then, it merges this entry with any recurring expenses and savings goals to provide a complete picture of the month's finances.
  const resolveEntry = useCallback(
    (y: number, m: number): MonthlyEntry => {
      const stored =
        monthsData.find((e) => e.year === y && e.month === m) ??
        emptyMonthlyEntry(y, m);
      return mergeMonthlyEntry(stored, recurringExpenses, savingsGoals);
    },
    [monthsData, recurringExpenses, savingsGoals],
  );

  const monthsForYear = useMemo(() => {
    const currentMonth = new Date().getMonth() + 1;
    const currentYear = new Date().getFullYear();
    const allMonths = Array.from({ length: 12 }, (_, i) =>
      resolveEntry(year, i + 1),
    );
    if (showAllMonths || year !== currentYear) {
      return allMonths;
    } else {
      return allMonths.filter((entry) => entry.month >= currentMonth);
    }
  }, [resolveEntry, year, showAllMonths]);

  // Reuses monthsForYear as-is, so the chart automatically follows the same
  // "rest of this year, or all of it once showAllMonths/a past year is picked"
  // rule the yearly planner already uses — no separate range logic needed.
  const trendData = useMemo(
    () =>
      monthsForYear.map((entry) => {
        const summary = summariseMonth(entry, baseNetMonthly);
        return {
          month: MONTH_NAMES[entry.month - 1].slice(0, 3),
          income: Math.round(summary.totalIncome),
          outgoings: Math.round(summary.totalOutgoings),
          savings: Math.round(summary.totalSavings),
          remaining: Math.round(summary.remaining),
        };
      }),
    [monthsForYear, baseNetMonthly],
  );

  const handleSaveMonth = useCallback(
    async (entry: MonthlyEntry) => {
      setSaveError(null);
      const toStore = stripAutoGenerated(entry);

      const res = await fetch("/api/monthly-entries", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(toStore),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        const message =
          data.error ??
          "Failed to save. Ensure the monthly_entries migration has been applied in Supabase.";
        setSaveError(message);
        throw new Error(message);
      }

      setMonthsData((prev) => {
        const rest = prev.filter(
          (m) => !(m.year === toStore.year && m.month === toStore.month),
        );
        return [...rest, toStore];
      });
      router.refresh();
    },
    [router],
  );

  return (
    <>
      <MonthDetailModal
        open={modalMonth !== null}
        year={year}
        month={modalMonth}
        resolveEntry={resolveEntry}
        baseNetMonthly={baseNetMonthly}
        onClose={() => setModalMonth(null)}
        onSaveMonth={handleSaveMonth}
        savingsGoals={savingsGoals}
        recurringExpenses={recurringExpenses}
        saveError={saveError}
      />

      <div className="min-h-screen bg-paper-canvas px-4 py-8 sm:px-8">
        <div className="mx-auto max-w-6xl">
          <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h1 className="font-display text-3xl font-bold text-ink-900">
                Welcome back, {firstName}!
              </h1>
              <p className="mt-1 max-w-xl text-sm text-ink-600">
                Ditch messy spreadsheets. Manage your tax codes, pension
                contributions, and monthly expenditures — properly ledgered.
              </p>
            </div>

            <div className="flex shrink-0 rounded-md border border-ink-200 bg-paper-card p-1 shadow-sm">
              <ViewToggle
                active={view === "yearly"}
                onClick={() => setView("yearly")}
                icon={<GridViewIcon />}
                label="Yearly View"
              />
              <ViewToggle
                active={view === "monthly"}
                onClick={() => setView("monthly")}
                icon={<CalendarIcon />}
                label="Monthly View"
              />
            </div>
          </header>

          {saveError ? (
            <p className="mb-4 rounded-md border border-ledger-200 bg-ledger-50 px-4 py-2 text-sm text-ledger-700">
              {saveError}
            </p>
          ) : null}

          <div className="mb-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
            <FinanceTrendChart
              data={trendData}
              subtitle={
                showAllMonths || year !== new Date().getFullYear()
                  ? `All of ${year}`
                  : `Rest of ${year}`
              }
            />
            <TakeHomeCard result={takeHome} currentMonthPay={currentMonthPay} />
          </div>

          {view === "yearly" ? (
            <YearlyPlannerSection
              year={year}
              onYearChange={setYear}
              months={monthsForYear}
              baseNetMonthly={baseNetMonthly}
              onZoomMonth={setModalMonth}
              showAllMonths={showAllMonths}
              onShowAllMonthsChange={() => setShowAllMonths(!showAllMonths)}
            />
          ) : (
            <MonthlyDetailView
              year={year}
              resolveEntry={resolveEntry}
              baseNetMonthly={baseNetMonthly}
              selectedMonth={selectedMonth}
              onMonthChange={setSelectedMonth}
              onSaveMonth={handleSaveMonth}
              savingsGoals={savingsGoals}
              recurringExpenses={recurringExpenses}
            />
          )}
        </div>
      </div>
    </>
  );
}

function ViewToggle({
  active,
  onClick,
  icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`inline-flex items-center gap-2 rounded px-4 py-2 text-sm font-medium transition ${
        active
          ? "bg-paper-card text-ledger-700 shadow-sm"
          : "text-ink-500 hover:text-ink-700"
      }`}
    >
      {icon}
      {label}
    </button>
  );
}
