"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { TakeHomeResult } from "@/lib/take-home/calculate";
import {
  mergeMonthlyEntry,
  stripAutoGenerated,
} from "@/lib/monthly/merge-recurring";
import type { FinancialInfo } from "@/app/setup/types";
import type { MonthlyEntry } from "@/types/monthlyPlan";
import { emptyMonthlyEntry } from "@/types/monthlyPlan";
import type { RecurringExpense, SavingsGoal } from "@/types/recurringBudget";
import { CalendarIcon, GridViewIcon } from "./icons";
import ProfileCard from "./profile-card";
import TakeHomeCard from "./take-home-card";
import MonthlyDetailView from "./monthly-detail-view";
import YearlyPlannerSection from "./yearly-planner-section";
import MonthDetailModal from "./month-detail-modal";

type ViewMode = "yearly" | "monthly";

type DashboardClientProps = {
  firstName: string;
  lastName: string;
  financialInfo: FinancialInfo;
  studentLoanLabel: string;
  lastUpdated: string;
  takeHome: TakeHomeResult;
  initialYear: number;
  initialMonthsData: MonthlyEntry[];
  recurringExpenses: RecurringExpense[];
  savingsGoals: SavingsGoal[];
  baseNetMonthly: number;
  currentMonthPay: {
    amount: number;
    payDateLabel: string;
  };
};

export default function DashboardClient({
  firstName,
  lastName,
  financialInfo,
  studentLoanLabel,
  lastUpdated,
  takeHome,
  initialYear,
  initialMonthsData,
  recurringExpenses,
  savingsGoals,
  baseNetMonthly,
  currentMonthPay,
}: DashboardClientProps) {
  const router = useRouter();
  const [view, setView] = useState<ViewMode>("yearly");
  const [year, setYear] = useState(initialYear);
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [monthsData, setMonthsData] = useState(initialMonthsData);
  const [modalMonth, setModalMonth] = useState<number | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    setMonthsData(initialMonthsData);
  }, [initialMonthsData]);

  const resolveEntry = useCallback(
    (y: number, m: number): MonthlyEntry => {
      const stored =
        monthsData.find((e) => e.year === y && e.month === m) ??
        emptyMonthlyEntry(y, m);
      return mergeMonthlyEntry(stored, recurringExpenses, savingsGoals);
    },
    [monthsData, recurringExpenses, savingsGoals],
  );

  const monthsForYear = useMemo(() => {
    return Array.from({ length: 12 }, (_, i) => resolveEntry(year, i + 1));
  }, [resolveEntry, year]);

  const handleSaveMonth = useCallback(
    async (entry: MonthlyEntry) => {
      setSaveError(null);
      const toStore = stripAutoGenerated(entry);

      const res = await fetch("/api/monthly-entries", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(toStore),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        const message =
          data.error ??
          "Failed to save. Ensure the monthly_entries migration has been applied in Supabase.";
        setSaveError(message);
        throw new Error(message);
      }

      setMonthsData((prev) => {
        const rest = prev.filter(
          (m) => !(m.year === toStore.year && m.month === toStore.month),
        );
        return [...rest, toStore];
      });
      router.refresh();
    },
    [router],
  );

  return (
    <>
      <MonthDetailModal
        open={modalMonth !== null}
        year={year}
        month={modalMonth}
        resolveEntry={resolveEntry}
        baseNetMonthly={baseNetMonthly}
        onClose={() => setModalMonth(null)}
        onSaveMonth={handleSaveMonth}
        savingsGoals={savingsGoals}
        saveError={saveError}
      />

      <div className="min-h-screen bg-[#eef1f6] px-4 py-8 sm:px-8">
        <div className="mx-auto max-w-6xl">
          <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h1 className="text-3xl font-bold text-slate-900">
                Welcome back, {firstName}!
              </h1>
              <p className="mt-1 max-w-xl text-sm text-slate-500">
                Ditch messy spreadsheets. Manage your tax codes, pension
                contributions, and monthly expenditures in a clean bento board.
              </p>
            </div>

            <div className="flex shrink-0 rounded-full border border-slate-200 bg-white p-1 shadow-sm">
              <ViewToggle
                active={view === "yearly"}
                onClick={() => setView("yearly")}
                icon={<GridViewIcon />}
                label="Yearly View"
              />
              <ViewToggle
                active={view === "monthly"}
                onClick={() => setView("monthly")}
                icon={<CalendarIcon />}
                label="Monthly View"
              />
            </div>
          </header>

          {saveError ? (
            <p className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">
              {saveError}
            </p>
          ) : null}

          <div className="mb-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
            <ProfileCard
              firstName={firstName}
              lastName={lastName}
              financialInfo={financialInfo}
              studentLoanLabel={studentLoanLabel}
              lastUpdated={lastUpdated}
            />
            <TakeHomeCard result={takeHome} currentMonthPay={currentMonthPay} />
          </div>

          {view === "yearly" ? (
            <YearlyPlannerSection
              year={year}
              onYearChange={setYear}
              months={monthsForYear}
              baseNetMonthly={baseNetMonthly}
              onZoomMonth={setModalMonth}
            />
          ) : (
            <MonthlyDetailView
              year={year}
              resolveEntry={resolveEntry}
              baseNetMonthly={baseNetMonthly}
              selectedMonth={selectedMonth}
              onMonthChange={setSelectedMonth}
              onSaveMonth={handleSaveMonth}
              savingsGoals={savingsGoals}
            />
          )}
        </div>
      </div>
    </>
  );
}

function ViewToggle({
  active,
  onClick,
  icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium transition ${
        active
          ? "bg-white text-violet-700 shadow-sm"
          : "text-slate-500 hover:text-slate-700"
      }`}
    >
      {icon}
      {label}
    </button>
  );
}
