import type { MonthlyEntry, BudgetLineItem } from "@/types/monthlyPlan";
import type { RecurringExpense, SavingsGoal } from "@/types/recurringBudget";

export function monthIndex(year: number, month: number): number {
  return year * 12 + month;
}

export function appliesToMonth(
  item: {
    startsFromYear: number | null;
    startsFromMonth: number | null;
    endsUntilYear: number | null;
    endsUntilMonth: number | null;
    createdAt: string;
  },
  year: number,
  month: number,
): boolean {
  const target = monthIndex(year, month);

  const start =
    item.startsFromYear != null && item.startsFromMonth != null
      ? monthIndex(item.startsFromYear, item.startsFromMonth)
      : (() => {
          const created = new Date(item.createdAt);
          return monthIndex(created.getFullYear(), created.getMonth() + 1);
        })();

  if (target < start) return false;

  if (item.endsUntilYear != null && item.endsUntilMonth != null) {
    if (target > monthIndex(item.endsUntilYear, item.endsUntilMonth))
      return false;
  }

  return true;
}

export function isAutoGeneratedLine(item: BudgetLineItem): boolean {
  return (
    item.id.startsWith("recurring-") || item.id.startsWith("savings-goal-")
  );
}

export function recurringToLineItem(expense: RecurringExpense): BudgetLineItem {
  return {
    id: `recurring-${expense.id}`,
    label: expense.label,
    amount: expense.amount,
    recurringExpenseId: expense.id,
  };
}

export function savingsGoalToLineItem(goal: SavingsGoal): BudgetLineItem {
  return {
    id: `savings-goal-${goal.id}`,
    label: goal.label,
    amount: goal.amount ?? 0,
    savingsGoalId: goal.id,
  };
}

/** Merge recurring expenses & savings goals into a stored monthly entry for display. */
export function mergeMonthlyEntry(
  entry: MonthlyEntry,
  recurring: RecurringExpense[],
  savingsGoals: SavingsGoal[],
): MonthlyEntry {
  const manualExpenditures = entry.expenditures.filter(
    (e) => !e.id.startsWith("recurring-"),
  );

  const overridesByGoal = new Map(
    entry.savings
      .filter((s) => s.savingsGoalId && !s.id.startsWith("savings-goal-"))
      .map((s) => [s.savingsGoalId!, s]),
  );

  const legacyManualSavings = entry.savings.filter((s) => !s.savingsGoalId);

  const recurringExpenditures = recurring
    .filter((r) => appliesToMonth(r, entry.year, entry.month))
    .map(recurringToLineItem);

  const goalSavings = savingsGoals
    .filter((g) => appliesToMonth(g, entry.year, entry.month))
    .map((g) => overridesByGoal.get(g.id) ?? savingsGoalToLineItem(g));

  return {
    ...entry,
    expenditures: [...recurringExpenditures, ...manualExpenditures],
    savings: [...goalSavings, ...legacyManualSavings],
  };
}

/** Strip display-only merged lines before persisting user edits. */
export function stripAutoGenerated(entry: MonthlyEntry): MonthlyEntry {
  return {
    ...entry,
    expenditures: entry.expenditures.filter(
      (e) => !e.id.startsWith("recurring-"),
    ),
    savings: entry.savings.filter((s) => !s.id.startsWith("savings-goal-")),
  };
}

export function mergeAllMonths(
  entries: MonthlyEntry[],
  recurring: RecurringExpense[],
  savingsGoals: SavingsGoal[],
): MonthlyEntry[] {
  return entries.map((e) => mergeMonthlyEntry(e, recurring, savingsGoals));
}

export function formatLastUpdated(iso: string | null | undefined): string {
  if (!iso) return "no data yet";
  try {
    return new Intl.DateTimeFormat("en-GB", {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(new Date(iso));
  } catch {
    return "no data yet";
  }
}
