import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { createClient } from "@/utils/supabase/server";
import type { BudgetLineItem, MonthlyEntry } from "@/types/monthlyPlan";
import { stripAutoGenerated } from "@/lib/monthly/merge-recurring";

function parseItems(value: unknown): BudgetLineItem[] {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (item): item is BudgetLineItem =>
      typeof item === "object" &&
      item !== null &&
      typeof item.id === "string" &&
      typeof item.label === "string" &&
      typeof item.amount === "number",
  );
}

export async function POST(req: Request) {
  const body = await req.json().catch(() => null);
  if (
    !body ||
    typeof body.year !== "number" ||
    typeof body.month !== "number"
  ) {
    return NextResponse.json({ ok: false, error: "invalid" }, { status: 400 });
  }

  const cookieStore = await cookies();
  const supabase = createClient(cookieStore);

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json(
      { ok: false, error: "unauthenticated" },
      { status: 401 },
    );
  }

  const entry: MonthlyEntry = {
    year: body.year,
    month: body.month,
    takeHomeSalary:
      body.takeHomeSalary != null ? Number(body.takeHomeSalary) : null,
    incomes: parseItems(body.incomes),
    expenditures: parseItems(body.expenditures),
    savings: parseItems(body.savings),
  };

  const toStore = stripAutoGenerated(entry);

  const { error } = await supabase.from("monthly_entries").upsert(
    {
      user_id: user.id,
      year: toStore.year,
      month: toStore.month,
      take_home_salary: toStore.takeHomeSalary ?? null,
      incomes: toStore.incomes,
      expenditures: toStore.expenditures,
      savings: toStore.savings,
    },
    { onConflict: "user_id,year,month" },
  );

  if (error) {
    console.error("monthly_entries upsert error:", error);
    return NextResponse.json(
      { ok: false, error: error.message },
      { status: 500 },
    );
  }

  return NextResponse.json({ ok: true });
}
