//TODO: Once this is all fully understood, use proper doc blocks

// Types: MonthlyEntry (a month in the monthly plan), BudgetLineItem (a line in the monthly plan)
import type { MonthlyEntry, BudgetLineItem } from "@/types/monthlyPlan";
// Type: SavingsGoal (a savings goal)
import type { SavingsGoal } from "@/types/savingsGoals";
// Type: RecurringExpense (a recurring expense)
import { RecurringExpense } from "@/types/recurringExpenses";

// Simple function to convert a year and month to a month index
// returned monthIndex is a single number so months can be compared with simple < and > operators.
// Just a number version of a year-month pair really
export function monthIndex(year: number, month: number): number {
  return year * 12 + month;
}

// Function to check if an savings goal/expenditure applies to a given month
// Used to filter recurring expenses and savings goals to the current month
export function appliesToMonth(
  // Full object contains more data but this is all we need
  item: {
    // Year the savings goal/expenditure started from
    startsFromYear: number | null;
    // The month the savings goal/expenditure started
    startsFromMonth: number | null;
    // The year the savings goal/expenditure ends
    endsUntilYear: number | null;
    // The month the savings goal/expenditure ends
    endsUntilMonth: number | null;
    // When this savings goal/expenditure was created
    createdAt: string;
  },
  // The year of entry (month we're operating on) (we're looking at July 2026, this value will be 2026 (number)) TODO: this seems inefficient
  year: number,
  // The month of entry (month we're operating on) (we're looking at July 2026, this value will be 7 (number))
  month: number,
): boolean {
  // Get current month's monthIndex, 24319 in this case (July 2026)
  const target = monthIndex(year, month);

  // Start =
  const start =
    //  Do we have an explicit start date? E.g. we could have March 2025 so yes we do
    item.startsFromYear != null && item.startsFromMonth != null
      ? // If we do: conert that start date into a monthIndex so we can compare. (24303 for March 2025)
        monthIndex(item.startsFromYear, item.startsFromMonth)
      : // If not, fallback to treating as it started when it was created using createdAt
        (() => {
          // This might be "2026-01-15T00:00:00Z" meaning midnight of 15th January 2026
          const created = new Date(item.createdAt);
          // we then convert it into a monthIndex value
          return monthIndex(created.getFullYear(), created.getMonth() + 1);
        })();

  // If the start was March 2025 then (24319 < 24303 ? No July 2026 is not before March 2025 so we skip this)
  // If it was target July 2026 and start was August 2026 then (24319 < 24320 ? Yes, August is after July #
  // so we will return false here and show that this savings goal/expenditure does NOT apply to this month)
  if (target < start) return false;

  // In the case of the first example, July 2026 is after March 2025 so we reach this section.
  // Then we check does this item have an explicit end year and end month?
  // If not then we skip this entirely and say yes if we've gotten this far then this DOES apply to this month.
  //
  // If we do have an explicit end year and month, it's time to check those.
  if (item.endsUntilYear != null && item.endsUntilMonth != null) {
    // if target (24319) is BIGGER than the monthValue representing the end date
    // In other words: if the end date was June 2026, the end was in the past.
    // The condition is fulfilled.
    if (target > monthIndex(item.endsUntilYear, item.endsUntilMonth))
      // and we say NO this savings goal/expenditure DOES NOT apply to this month.
      return false;
  }
  // If we reach this point, the savings goal/expenditure DOES apply to this month.
  return true;
}

// Function to check if a BudgetLineItem is auto-generated (from recurring expenses or savings goals)
// We know this because recurringToLineItem and savingsGoalToLineItem both prefix the id with "recurring-" or "savings-goal-"
export function isAutoGeneratedLine(item: BudgetLineItem): boolean {
  return (
    item.id.startsWith("recurring-") || item.id.startsWith("savings-goal-")
  );
}

// Tag BudgetLineItem as recurring expense
export function recurringToLineItem(expense: RecurringExpense): BudgetLineItem {
  // Build a brand new BudgetLineItem from the RecurringExpense we were given.
  return {
    // Prefix with "recurring-" so isAutoGeneratedLine (and the checks for "recurring-" prefix
    // dotted around this file) can tell this line was generated, not typed by the user.
    id: `recurring-${expense.id}`,
    // Keep label same
    label: expense.label,
    // Keep amoutn same
    amount: expense.amount,
    // Keep a reference back to the original recurring expense id, separate from the prefixed line item id above,
    // so we can still look the source expense up later (e.g. to build an override).
    recurringExpenseId: expense.id,
  };
}

// Tag BudgetLineItem as savings goal
export function savingsGoalToLineItem(goal: SavingsGoal): BudgetLineItem {
  // Same idea as recurringToLineItem above, just for a SavingsGoal instead.
  return {
    id: `savings-goal-${goal.id}`, //line item id
    label: goal.label,
    // goal.amount can be null/undefined (e.g. a goal with no fixed monthly contribution yet),
    // so we fall back to 0 rather than letting an undefined amount leak into the totals.
    amount: goal.amount ?? 0,
    savingsGoalId: goal.id, // savings goal id
  };
}

/** Merge recurring expenses & savings goals into a stored monthly entry for display.
 *
 * The database only stores what the user explicitly typed in for a month, MANUAL expenditures/savings/income.
 *
 * Recurring expenses/savings goals are stored separately.
 *
 * When the dashbaord needs to show a month, it can't just display the month data from supabase, it would be missing all recurring stuff.
 * So resolveEntry fetches the month data, or creates an empty month if it doesn't exist, then calls
 * mergeMonthlyEntry(stored, recurringExpenses, savingsGoals) to combine manual BudgetLineItems with auto-generated
 * ones as defined through the Savings Goals and Recurring Expenses pages.
 *
 */
export function mergeMonthlyEntry(
  // The monthly entry
  entry: MonthlyEntry,
  // Recurring expenses we'll work with
  recurring: RecurringExpense[],
  // Savings goals we'll work with
  savingsGoals: SavingsGoal[],
): MonthlyEntry {
  // Keep only the expenditures the user typed in themselves, NOT any auto-generated recurring expenses
  // (the stored entry may already have "recurring-" lines baked in from a previous merge/save, so we
  // strip them back out here before we regenerate them fresh below).

  // NOTE: This is defensive, stripAutoGenerated should be called before the last time an entry (month data) was saved
  // so this isn't requireq
  //
  // Also exclude anything tagged with a recurringExpenseId — those are per-month
  // overrides (see overridesByRecurring below), not genuinely manual entries, even
  // though their id isn't "recurring-" prefixed.
  const manualExpenditures = entry.expenditures.filter(
    (e) => !e.id.startsWith("recurring-") && !e.recurringExpenseId,
  );

  // entry.savings EXAMPLE:
  // "savings": [
  //   {
  //     "id": "cf92ae05-3f4b-4006-821b-c81f0fa4a47d",
  //     "label": "Wedding/EF",
  //     "amount": 10,
  //     "savingsGoalId": "318e713f-2fd9-4772-ab63-d2642a08317b"
  //   }
  // ]

  // After filter:
  // Wedding/EF does have a savingsGoalId AND its id does not start with savings-goal-
  // because it is not an auto-generated line item.

  // This is a manually-edited savings line that's still tied to a real savings goal
  // (e.g. the user bumped this month's Wedding/EF contribution up from the goal default).
  // We build a Map keyed by savingsGoalId -> the override line item, so that further down
  // we can quickly check "does this goal have a manual override this month?" in O(1) instead
  // of re-scanning entry.savings for every goal.
  const overridesByGoal = new Map(
    entry.savings
      .filter((s) => s.savingsGoalId && !s.id.startsWith("savings-goal-")) // take savingsGoals with id and the show they are NOT auto-generated
      .map((s) => [s.savingsGoalId!, s]),
  );
  // RESULTING MAP MAY LOOK A BIT LIKE THIS
  // [
  //
  //   [
  //    "318e713f-2fd9-4772-ab63-d2642a08317b",
  //    {
  //      id: "cf92ae05-...",
  //      label: "Wedding/EF",
  //      amount: 10,
  //      savingsGoalId: "318e713f-..."
  //    }
  //   ],
  //
  //   ...
  // ]

  // Savings lines with no savingsGoalId at all are old/manual one-off savings entries that were
  // never tied to a goal in the first place
  // These aren't touched by the goal merging logic below, so we keep them around as-is.
  //
  // PURELY DEFENSIVE PROGRAMMING
  const legacyManualSavings = entry.savings.filter((s) => !s.savingsGoalId);

  // Same idea as overridesByGoal above, but for recurring expenses: a manually-edited
  // expenditure line that's still tied to a real recurring expense (e.g. this month's
  // electricity bill came in £5 higher than usual).
  const overridesByRecurring = new Map(
    entry.expenditures
      .filter((e) => e.recurringExpenseId && !e.id.startsWith("recurring-"))
      .map((e) => [e.recurringExpenseId!, e]),
  );

  // Work out which recurring expenses are actually active for this entry's year/month,
  // then for each one either use the manual override we found above (if the user has
  // already customised this month's amount) or fall back to the expense's default
  // amount via recurringToLineItem.
  const recurringExpenditures = recurring
    .filter((r) => appliesToMonth(r, entry.year, entry.month))
    .map((r) => overridesByRecurring.get(r.id) ?? recurringToLineItem(r));

  // Same idea, but for savings goals: work out which goals are active this month, then for each
  // one either use the manual override we found above (if the user has already customised this
  // month's contribution) or fall back to the goal's default amount via savingsGoalToLineItem.
  const goalSavings = savingsGoals
    .filter((g) => appliesToMonth(g, entry.year, entry.month))
    .map((g) => overridesByGoal.get(g.id) ?? savingsGoalToLineItem(g));

  // Stitch everything back together into a new MonthlyEntry for display:
  // spread the original entry first (keeps year, month, incomes, takeHomeSalary etc. untouched),
  // then overwrite expenditures/savings with the freshly merged lists.
  // Auto-generated lines go first, followed by the user's own manually-typed lines.
  return {
    ...entry,
    expenditures: [...recurringExpenditures, ...manualExpenditures],
    savings: [...goalSavings, ...legacyManualSavings],
  };
}

/** Strip display-only merged lines before persisting user edits. */
// We never want auto-generated recurring/savings goals saved back to storage (next time we load, we'd regenerate
// them anyway, and any edit to a recurring expense/savings goal would go stale). So before
// writing a MonthlyEntry back out, we run it through here to drop anything auto-generated.
export function stripAutoGenerated(entry: MonthlyEntry): MonthlyEntry {
  return {
    // Keep year, month, takeHomeSalary, incomes etc. exactly as they were.
    ...entry,
    // Drop any expenditure line whose id was tagged with "recurring-" by recurringToLineItem.
    expenditures: entry.expenditures.filter(
      (e) => !e.id.startsWith("recurring-"),
    ),
    // Drop any savings line whose id was tagged with "savings-goal-" by savingsGoalToLineItem.
    // Note this keeps manual overrides (they're keyed by savingsGoalId, not this id prefix)
    // and legacy manual savings (no savingsGoalId at all) intact, same as before.
    savings: entry.savings.filter((s) => !s.id.startsWith("savings-goal-")),
  };
}

// Convenience wrapper for running mergeMonthlyEntry over a whole list of months at once,
// e.g. the full year of entries shown on the yearly planner. recurring and savingsGoals
// are the same for every month here, only the entry itself changes per call.
export function mergeAllMonths(
  entries: MonthlyEntry[],
  recurring: RecurringExpense[],
  savingsGoals: SavingsGoal[],
): MonthlyEntry[] {
  return entries.map((e) => mergeMonthlyEntry(e, recurring, savingsGoals));
}
