// Pure builder for the sample dataset every "Try demo" visitor gets. No I/O here —
// seed-user.ts does the writing — so the shapes can be checked without a database.
//
// Everything is placed relative to `now` (via month offsets) so the demo never looks stale.
//
// Row-building contract with mergeMonthlyEntry / stripAutoGenerated (utils/monthly/merge-recurring.ts):
//   - Stored lines get random ids, never a "recurring-" / "savings-goal-" prefix.
//   - A per-month override carries the REAL parent id in recurringExpenseId / savingsGoalId,
//     so parents have to be inserted first and their ids read back (see materializeMonthlyRows).
//   - At most one override per parent per month, and only in months where the parent applies.
//   - The bonus is modelled only as takeHomeSalary (+ note), never as an extra income line.

import { createInitialPayload } from "@/app/setup/utils";
import type {
  FinancialProfilePayload,
  PensionContribution,
} from "@/types/financialProfile";
import type { BudgetLineItem } from "@/types/monthlyPlan";
import {
  SAVINGS_GOAL_NOTES_MAX_LENGTH,
  type InterestFrequency,
} from "@/types/savingsGoals";
import {
  monthIndex,
  monthIndexToYearMonth,
} from "@/utils/monthly/merge-recurring";
import {
  calculateTakeHomeForMonth,
  resolveTaxYearForCalendarMonth,
} from "@/utils/take-home/calculate";

// Stable labels: the later guided tour and the override plans below key off these.
export const DEMO_LABELS = {
  rent: "Rent",
  councilTax: "Council tax",
  energy: "Gas & electricity",
  broadband: "Broadband & mobile",
  groceries: "Groceries & household",
  leisure: "Eating out & leisure",
  carTax: "Car tax",
  carInsurance: "Car insurance",
  emergencyFund: "Emergency fund",
  houseDeposit: "House deposit (LISA)",
} as const;

export type DemoRecurringExpenseRow = {
  label: string;
  amount: number;
  interval_months: number;
  starts_from_year: number | null;
  starts_from_month: number | null;
  ends_until_year: number | null;
  ends_until_month: number | null;
};

export type DemoSavingsGoalRow = {
  label: string;
  amount: number;
  uses_variable_amount: boolean;
  current_balance: number;
  earns_interest: boolean;
  interest_rate: number;
  interest_frequency: InterestFrequency;
  notes: string | null;
  starts_from_year: number | null;
  starts_from_month: number | null;
  ends_until_year: number | null;
  ends_until_month: number | null;
};

export type DemoSalaryChangeRow = {
  annual_income: number;
  tax_code: string;
  pension: PensionContribution;
  effective_from_year: number | null;
  effective_from_month: number | null;
  ends_until_year: number;
  ends_until_month: number;
};

export type DemoLine = { label: string; amount: number };

// Overrides name their parent by label; materializeMonthlyRows swaps it for the real id.
export type DemoOverride = { parentLabel: string; amount: number };

export type DemoMonthPlan = {
  year: number;
  month: number;
  incomes: DemoLine[];
  expenses: DemoLine[];
  expenseOverrides: DemoOverride[];
  savingsOverrides: DemoOverride[];
  takeHomeSalary: number | null;
  takeHomeSalaryNote: string | null;
};

export type DemoSeed = {
  profile: {
    first_name: string;
    last_name: string;
    date_of_birth: string;
  };
  // id is a placeholder — the writer sets it to the real user id.
  financialPayload: FinancialProfilePayload;
  taxYear: string;
  recurringExpenses: DemoRecurringExpenseRow[];
  savingsGoals: DemoSavingsGoalRow[];
  salaryChanges: DemoSalaryChangeRow[];
  months: DemoMonthPlan[];
};

export type MonthlyEntryInsertRow = {
  user_id: string;
  year: number;
  month: number;
  take_home_salary: number | null;
  take_home_salary_note: string | null;
  incomes: BudgetLineItem[];
  expenditures: BudgetLineItem[];
  savings: BudgetLineItem[];
};

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

const PENSION: PensionContribution = {
  type: "percentage",
  value: 5,
  scheme: "auto-enrolment",
  basedOnQualifyingEarnings: true,
  includeOvertime: false,
  includeBonus: false,
  includeCashAllowances: false,
};

const EMERGENCY_FUND_NOTE =
  "Building up six months of essential spending as a safety net. Held in an easy-access account that pays interest monthly. Topped up a little extra when there's room in the month.";

const HOUSE_DEPOSIT_NOTE =
  "Lifetime ISA towards a first home. The government adds 25% to what goes in, so the monthly figure is roughly what makes the most of the annual limit. Planning to buy in about three years.";

export function buildDemoSeed(now: Date): DemoSeed {
  const nowYear = now.getFullYear();
  const nowMonth = now.getMonth() + 1;
  const nowIdx = monthIndex(nowYear, nowMonth);
  // Offset in months from "this month" (negative = past) as a year/month pair.
  const at = (offset: number) => monthIndexToYearMonth(nowIdx + offset);

  // --- Persona -------------------------------------------------------------
  const dobYear = nowYear - 29;
  const birthdayPassed =
    nowMonth > 3 || (nowMonth === 3 && now.getDate() >= 14);
  const age = birthdayPassed ? 29 : 28;
  const taxYear = resolveTaxYearForCalendarMonth(nowYear, nowMonth);

  const payload = createInitialPayload("");
  payload.userInfo = {
    firstName: "Alex",
    lastName: "Morgan",
    dob: `${dobYear}-03-14`,
    age,
  };
  payload.financialInfo = {
    ...payload.financialInfo,
    annualIncome: 52000,
    payDate: { dayOfMonth: 28 },
    taxYear,
    taxCode: "1257L",
    studentLoanPlan: {
      plan1: false,
      plan2: true,
      plan4Scotland: false,
      plan5: false,
      postgraduate: false,
    },
    pension: { ...PENSION },
  };

  // --- Recurring expenses --------------------------------------------------
  // starts_from is always explicit: a null start falls back to createdAt, which would
  // shift the every-N-months anchor to whenever the demo was seeded.
  const monthly = (label: string, amount: number): DemoRecurringExpenseRow => ({
    label,
    amount,
    interval_months: 1,
    starts_from_year: at(-12).year,
    starts_from_month: at(-12).month,
    ends_until_year: null,
    ends_until_month: null,
  });
  const recurringExpenses: DemoRecurringExpenseRow[] = [
    monthly(DEMO_LABELS.rent, 1100),
    monthly(DEMO_LABELS.councilTax, 142),
    monthly(DEMO_LABELS.energy, 95),
    monthly(DEMO_LABELS.broadband, 45),
    monthly(DEMO_LABELS.groceries, 380),
    monthly(DEMO_LABELS.leisure, 150),
    // Anchors chosen so each lands in an upcoming month: car tax at +1 and +7, insurance at +4.
    {
      label: DEMO_LABELS.carTax,
      amount: 105,
      interval_months: 6,
      starts_from_year: at(-5).year,
      starts_from_month: at(-5).month,
      ends_until_year: null,
      ends_until_month: null,
    },
    {
      label: DEMO_LABELS.carInsurance,
      amount: 486,
      interval_months: 12,
      starts_from_year: at(-8).year,
      starts_from_month: at(-8).month,
      ends_until_year: null,
      ends_until_month: null,
    },
  ];

  // --- Savings goals (fixed amounts only) -----------------------------------
  const savingsGoals: DemoSavingsGoalRow[] = [
    {
      label: DEMO_LABELS.emergencyFund,
      amount: 250,
      uses_variable_amount: false,
      current_balance: 4200,
      earns_interest: true,
      interest_rate: 4.2,
      interest_frequency: "monthly",
      notes: EMERGENCY_FUND_NOTE,
      starts_from_year: at(-12).year,
      starts_from_month: at(-12).month,
      ends_until_year: null,
      ends_until_month: null,
    },
    {
      label: DEMO_LABELS.houseDeposit,
      amount: 333,
      uses_variable_amount: false,
      current_balance: 7800,
      earns_interest: true,
      interest_rate: 3.5,
      interest_frequency: "annually",
      notes: HOUSE_DEPOSIT_NOTE,
      starts_from_year: at(-12).year,
      starts_from_month: at(-12).month,
      ends_until_year: at(35).year,
      ends_until_month: at(35).month,
    },
  ];
  for (const goal of savingsGoals) {
    if (goal.notes && goal.notes.length > SAVINGS_GOAL_NOTES_MAX_LENGTH) {
      throw new Error(`demo seed: note too long for "${goal.label}"`);
    }
  }

  // --- Salary history: two closed, contiguous windows before the live profile ---
  const salaryChanges: DemoSalaryChangeRow[] = [
    {
      annual_income: 41000,
      tax_code: "1257L",
      pension: { ...PENSION },
      effective_from_year: null,
      effective_from_month: null,
      ends_until_year: at(-19).year,
      ends_until_month: at(-19).month,
    },
    {
      annual_income: 46500,
      tax_code: "1257L",
      pension: { ...PENSION },
      effective_from_year: at(-18).year,
      effective_from_month: at(-18).month,
      ends_until_year: at(-7).year,
      ends_until_month: at(-7).month,
    },
  ];

  // --- Monthly plans: only what a person would actually type ---------------
  const plan = (
    offset: number,
    parts: Partial<Omit<DemoMonthPlan, "year" | "month">>,
  ): DemoMonthPlan => ({
    ...at(offset),
    incomes: [],
    expenses: [],
    expenseOverrides: [],
    savingsOverrides: [],
    takeHomeSalary: null,
    takeHomeSalaryNote: null,
    ...parts,
  });

  // Month +2 carries the bonus: take-home is the normal figure plus the net bonus.
  const bonusMonth = at(2);
  const bonusBaseNet = round2(
    calculateTakeHomeForMonth(
      payload.financialInfo,
      bonusMonth.year,
      bonusMonth.month,
    ).netMonthly,
  );

  const months: DemoMonthPlan[] = [
    plan(-2, {
      incomes: [{ label: "Birthday money", amount: 75 }],
      expenses: [{ label: "Dentist", amount: 65 }],
    }),
    plan(-1, { incomes: [{ label: "Sold bike", amount: 180 }] }),
    plan(0, { expenses: [{ label: "Weekend away", amount: 210 }] }),
    plan(2, {
      expenseOverrides: [{ parentLabel: DEMO_LABELS.groceries, amount: 470 }],
      takeHomeSalary: round2(bonusBaseNet + 980),
      takeHomeSalaryNote:
        "Annual bonus (£2,000 gross) paid in this month's payroll",
    }),
    plan(3, {
      savingsOverrides: [{ parentLabel: DEMO_LABELS.emergencyFund, amount: 100 }],
    }),
    plan(4, {
      expenseOverrides: [{ parentLabel: DEMO_LABELS.carInsurance, amount: 462 }],
    }),
    plan(5, { expenses: [{ label: "Wedding gift", amount: 90 }] }),
    plan(6, {
      savingsOverrides: [{ parentLabel: DEMO_LABELS.houseDeposit, amount: 400 }],
    }),
    plan(7, { incomes: [{ label: "HMRC tax refund", amount: 312 }] }),
    plan(8, { expenses: [{ label: "Car service", amount: 180 }] }),
    plan(9, { expenses: [{ label: "Concert tickets", amount: 85 }] }),
  ];

  return {
    profile: {
      first_name: payload.userInfo.firstName,
      last_name: payload.userInfo.lastName,
      date_of_birth: payload.userInfo.dob,
    },
    financialPayload: payload,
    taxYear,
    recurringExpenses,
    savingsGoals,
    salaryChanges,
    months,
  };
}

/**
 * Turns the month plans into monthly_entries rows. `ids` maps parent label -> the real row id
 * read back after the parents were inserted. `newId` is injectable so checks can be deterministic.
 */
export function materializeMonthlyRows(
  plans: DemoMonthPlan[],
  ids: { recurring: Map<string, string>; goals: Map<string, string> },
  userId: string,
  newId: () => string = () => crypto.randomUUID(),
): MonthlyEntryInsertRow[] {
  const parentId = (map: Map<string, string>, label: string, kind: string) => {
    const id = map.get(label);
    if (!id) throw new Error(`demo seed: no ${kind} id for "${label}"`);
    return id;
  };

  return plans.map((p) => ({
    user_id: userId,
    year: p.year,
    month: p.month,
    take_home_salary: p.takeHomeSalary,
    take_home_salary_note: p.takeHomeSalaryNote,
    incomes: p.incomes.map((l) => ({ id: newId(), ...l })),
    expenditures: [
      ...p.expenseOverrides.map((o) => ({
        id: newId(),
        label: o.parentLabel,
        amount: o.amount,
        recurringExpenseId: parentId(ids.recurring, o.parentLabel, "recurring expense"),
      })),
      ...p.expenses.map((l) => ({ id: newId(), ...l })),
    ],
    savings: p.savingsOverrides.map((o) => ({
      id: newId(),
      label: o.parentLabel,
      amount: o.amount,
      savingsGoalId: parentId(ids.goals, o.parentLabel, "savings goal"),
    })),
  }));
}
